language: python

jobs:
    include:
        - os: linux
          python: "3.6"
          env: CONDA_ENV=py36
        - os: linux
          python: "3.7"
          env: CONDA_ENV=py37
        - os: osx
          language: generic
          env: CONDA_ENV=py36
        - os: osx
          language: generic
          env: CONDA_ENV=py37

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export MINICONDAVERSION="MacOSX"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export MINICONDAVERSION="Linux"; fi
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDAVERSION
- wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDAVERSION-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a

install:
- conda env create --file ci/environment-$CONDA_ENV.yml
- source activate cmpdata

script: pytest

