language: python
sudo: required
dist: trusty
python:
 - 3.6
 - 3.7

os:
 - osx
 - linux
#jobs:
#    include:
#        # Use generic language for osx
#        - os: osx
#          language: generic
#          env: TOXENV=py36
#      
#        - os: osx
#          language: generic
#          env: TOXENV=py37

before_install:
 - CI/before_install.sh

install:
 - export MINICONDA=$HOME/miniconda
 - export PATH="$MINICONDA/bin:$PATH"
 - source activate testenv
 - conda install -c conda-forge xesmf
 - conda install -c conda-forge dask netCDF4
 - conda install -c conda-forge xesmf esmpy=7.1.0
 - pip install pytest

script: pytest

