language: python
sudo: required
dist: trusty
python:
 - 3.6
 - 3.7

matrix:
    include:
        # Use generic language for osx
        - os: osx
          language: generic
          env: TOXENV=py36
      
        - os: osx
          language: generic
          env: TOXENV=py37

before_install:
- if [ "$TRAVIS_OS_NAME" = linux ]; then
    sudo apt-get update
    MINICONDAVERSION="Linux"
else
    MINICONDAVERSION="MacOSX"
fi

- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  wget https://repo.continuum.io/miniconda/Miniconda2-latest-$MINICONDAVERSION-x86_64.sh -O miniconda.sh;
else
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDAVERSION-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels conda-forge
# Useful for debugging any issues with conda
- conda info -a

- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
 - export MINICONDA=$HOME/miniconda
 - export PATH="$MINICONDA/bin:$PATH"
 - source activate testenv
 - conda install -c conda-forge xesmf
 - conda install -c conda-forge dask netCDF4
 - conda install -c conda-forge xesmf esmpy=7.1.0

install:
 - pip install pytest

script: pytest

