language: python

jobs:
    include:
        # Use generic language for osx
        - os: osx
          language: generic
          env: TOXENV=py36

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export MINICONDAVERSION="MacOSX"; fi
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- export TRAVIS_PYTHON_VERSION="3.6"
#- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- wget --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDAVERSION-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- echo "Python version var"
- echo $TRAVIS_PYTHON_VERSION
- echo $MINICONDAVERSION
- conda create -n test python=$TRAVIS_PYTHON_VERSION
- source activate test

install:
- conda install -c conda-forge xesmf
- conda install -c conda-forge dask netCDF4
- conda install -c conda-forge xesmf esmpy=7.1.0

script: pytest

